### ISSUE TITLE
getting started

### ISSUE THREAD

**Issue by eikaramba** [MacFJA/svelte-adapter-neutralino#2]
this is really great! however beeing new to neutralino i wasn't able to directly make it work. i am using
npm init svelte@next my-app
then use the skeleton app and adapt my svelte.config.js file.

when doing npm run build i now get
`ENOENT: no such file or directory, open '.svelte-kit\neutralino\neutralino.config.json'`

might be good to add some basic getting started steps to the readme?

**Comment by MacFJA** [comment]
It didn't work with the default values 🤔 

I also see that you are on windows, maybe it's the issue.

----

For the **Getting started**,
I don't have much to put in it, you just have to install the dependency, and use it in the `svelte.config.js`.
You have few options to configure the result app, but nothing too complicated.

----

But you have an error, and not message to help you to figure out what the cause is, so definitely it miss something

**Comment by eikaramba** [comment]
thanks for the quick response. interesting to see that it should have worked. so i don't need to put thie neutralino.config.json file manually somewhere? you are right i am on windows, is there anything i can debug? maybe i am able to pinpoint the problem

**Comment by MacFJA** [comment]
I think I found the issue.

I use _"raw"_ Unix command, so of course it don't work on Windows.

I will fix that, but I don't have a Windows to test it

**Comment by eikaramba** [comment]
i also have found out something. once i create the .svelte-kit/neutralino folder manually it works ;)

mhm okay strange, there is no /build folder directly in the root folder
![grafik](https://user-images.githubusercontent.com/1320525/146839919-54886a1e-ad18-4abe-a9fe-e18515baf633.png)
i found the exe file however under \.svelte-kit\neutralino\dist\Svelte Kit

**Comment by MacFJA** [comment]
Yes, probably for the same reason.

The lines that I have to change are:
https://github.com/MacFJA/svelte-adapter-neutralino/blob/ecde7d7c8e2fc178f3dd4cd49a0c5c0723481bd6/index.js#L59-L60
https://github.com/MacFJA/svelte-adapter-neutralino/blob/ecde7d7c8e2fc178f3dd4cd49a0c5c0723481bd6/index.js#L116-L117

The `cp` don't exist on Windows, I have to change to something else

**Comment by MacFJA** [comment]
But in the mean time, the built application is in `.svelte-kit\neutralino\dist`

**Comment by MacFJA** [comment]
@eikaramba I just push the version `0.1.1`. Can you try again ?

**Comment by eikaramba** [comment]
it works now :)
